version: "3"

services:
  server:
    image: noam6421/server
    ports:
      - "3001:3001"
  client:
    image: noam6421/client
    ports:
      - "443:443"
    stdin_open: true 
    depends_on:
      - server
    links:
      - server 