version: "3"

services:
  server:
    build: .
    ports:
      - 3001:3001
  client:
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - server
    links:
      - server 