# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
    
      - name: Install dependencies
        run: npm install

      - name: docker login
        uses: actions-hub/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Build page
        run: npm run build
        env:
          CI: false
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}

      - script: |
          - docker build -t noam6421/server:latest \
          --build-arg PORT_ARG=${{ secrets.PORT }} \
          --build-arg DATABASE_URL_ARG=${{ secrets.DATABASE_URL }} \
          --build-arg GRAPHQL_URL_ARG=${{ secrets.GRAPHQL_URL }} \
          --build-arg TEST_ARG=${{ secrets.TEST }} .
        displayName: 'docker build'
      - name: docker push
        uses: actions-hub/docker@master
        with:
          args: push noam6421/server:latest
